services:
  nonebot:
    image: zecyel/fumo:latest
    ports:
      - "12345:12345"
    env_file:
      - .env.prod
    environment:
      ENVIRONMENT: prod
      HOST: "0.0.0.0"
      PORT: "12345"
    restart: always